### ISSUE TITLE
Error fetching path to FASTA file

### ISSUE THREAD

**Issue by TylerSagendorf** [PNNL-Comp-Mass-Spec/PNNL.DMS.utils#16]
**Minimum reproducible example:**
```
fst_path <- PNNL.DMS.utils::path_to_FASTA_used_by_DMS(4429)
```
**Results in the following error:**
<img src="https://user-images.githubusercontent.com/57922480/211676418-74de6d74-061c-491d-96de-a5ac602b7659.png" width = 600>

**Comment by alchemistmatt** [comment]
As part of a long-term effort to migrate DMS from SQL Server to PostgreSQL, I recently removed spaces from column names in all of the views used by the DMS website.  View `V_Analysis_Job_Detail_Report_2` is one of those views.  Here are some of the new column names:
* job
* dataset
* experiment
* organism
* organism_db
* protein_collection_list

You can find the complete list here:
https://github.com/PNNL-Comp-Mass-Spec/DBSchema_DMS/blob/master/DMS5/V_Analysis_Job_Detail_Report_2.sql

As you can see, the column names are also now lowercase.  Since the names no longer have spaces, you should remove the square brackets from your query, giving
```sql
SELECT organism_db, organism_db_storage_path
FROM V_Analysis_Job_Detail_Report_2
WHERE Job = 2077223
```
SQL Server allowed square bracket quoted names, while PostgreSQL does not (it uses double quotes).

Also, it would be better if you used view `V_Analysis_Job_Export`, like this:
```sql
SELECT Organism, OrganismDBName
FROM V_Analysis_Job_Export
WHERE Job = 2077223
```

I try not to rename columns in "Export" views, while I readily will rename/add/remove columns from "Detail Report" and "List Report" views.

Note that query results from PostgreSQL views will have lowercase column names, even if your query text has uppercase column names.
